---
secure:
  required_reviews: 1
  requires_mfa: true
  requires_verified: true
  upstream_repository: base/web
  branches:
    - staging

build:
  engines:
    - BaldurECR:
        name: web
        path: ./apps/web/Dockerfile
        architecture: arm64
  multi_arch: true

operate:
  slack_channels:
    - '#base-codeflow-notifications'
