# .yarnrc.yml - Yarn v3 Configuration File

# --- General Settings ---

# Disables the global cache, forcing Yarn to use the local cache only.
enableGlobalCache: false

# Disables telemetry data reporting for usage metrics.
enableTelemetry: false

# Specifies the package installation strategy (linker). 
# 'node-modules' provides compatibility with traditional tools not compatible with PnP.
# NOTE: Using 'pnp' would offer faster installation and stricter dependency control.
nodeLinker: node-modules

# --- Plugins ---

plugins:
  # Enables interactive command-line tools (e.g., `yarn dlx`).
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  # Enables monorepo and workspace management tools (e.g., `yarn workspaces foreach`).
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

# --- Yarn Version Path ---

# Specifies the path to the Yarn binary used for this project.
# Using a specific version (3.5.0) ensures deterministic behavior across environments.
yarnPath: .yarn/releases/yarn-3.5.0.cjs
