name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Tests
        run: |
          yarn install 
          yarn test
